const fs = require('fs');
const path = 'database/seeders/LabTestsSeeder.php';
let data = fs.readFileSync(path, 'utf8');
const mapping = {
  '(Free T4) free thyroxine': 'pmol/L',
  '(Mg) Magnesium': '1.82 - 2.43',
  'ABG': 'Rebort',
  'Activated Partial Thromboplastin Time (APTT)': 'Sec',
  'Adrenocorticotropic Hormone (ACTH)': 'pg/mI',
  'Albumin': 'g/dL',
  'Alkaline Phosphatase(ALP)': 'U/L',
  'ALT/GPT': 'U/L',
  'AMA (Antimitochondrial Antibody)': 'AU/mL',
  'Amylase': 'U/L',
  'ANA': 'U/mL',
  'ANA panel': 'Rebort',
  'Anti Diuretic hormone (ADH)': 'pg/mL',
  'Anti-a-Gliadin IgA': 'U/mL',
  'Anti-a-Gliadin IgG': 'U/mL',
  'Anti-Cardiolipin IgG': 'U/mL',
  'Anti-Cardiolipin IgM': 'U/mL',
  'Anti-CCP': 'U/mL',
  'Anti-Mullerian Hormone (AMH)': 'ng/mL',
  'Anti-Peroxidase (Anti-TPO)': 'U/mL',
  'Anti-Thyroglobulin (Anti TG)': 'IU/mL',
  'ASOT': 'IU/mL',
  'AST/GOT': 'U/L',
  'Beta-HCG': 'μIU/mL',
  'Bilirubin (Direct)': 'mg/dl',
  'Bilirubin (Indirect)': 'mg/dl',
  'Bilirubin (Total)': 'mg/dl',
  'Bleeding Time': 'Min',
  'Blood Culture': 'Rebort',
  'Blood Group (ABO)': 'Text',
  'BNP': 'pg/mL',
  'Brucella IgG': 'IU/mL',
  'Brucella IgM': 'IU/mL',
  'Brucella Test (Rose Bengal)': 'Test',
  'CA125': 'U/mL',
  'CA15-3': 'U/mL',
  'CA19.9': 'U/mL',
  'Calcitonin': 'Pg/ml',
  'Calcium': 'mg/dl',
  'Calprotectin (Stool)': 'Text',
  'Cardiac Troponin I titer': 'ng/L',
  'Cardiolipin IgA': 'U/mL',
  'CBC 3 Diff.': 'Rebort',
  'CBC 5 Diff.': 'Rebort',
  'CEA': 'ng/mL',
  'Ceruloplasmin': 'mg/dL',
  'Chloride (Cl)': 'mmol/L',
  'Cholesterol': 'mg/dL',
  'CK-MB': 'U/L',
  'CMV IgG': 'U/mL',
  'CMV IgM': 'U/mL',
  'Complement 3 (C3)': 'g/L',
  'Complement 4 (C4)': 'g/L',
  'Copper': 'ug/dL',
  'Cortisol': 'nmol/L',
  'Covid -19 Ag': 'Text',
  'C-Peptide': 'ng/mL',
  'C-Reactive Protein titer (CRP)': 'mg/L',
  'creatine phosphokinase CK (CPK)': 'U/L',
  'Creatinine': 'mg/dl',
  'CRP latex': 'Text',
  'D-Dimer': 'ug/mL',
  'DHEA-S': 'µg/dL',
  'ESR': 'mm/hr',
  'Estradiol (E2)': 'pg/mL',
  'Fasting Blood Sugar (FBS)': 'mg/dl',
  'Ferritin': 'ng/ml',
  'FOB (Fecal Occult Blood)': 'Text',
  'Free PSA': 'ng/mL',
  'Free T3': 'pmol/L',
  'FSH': 'mIU/mL',
  'General Stool Examination (GSE)': 'Rebort',
  'General Urine Examination (GUE)': 'Rebort',
  'Globulin': 'g/dL',
  'H.Pylori Ab': 'Text',
  'H.Pylori Ag': 'Text',
  'HbA1c': '%',
  'HBeAb': 'Text',
  'HBeAg': 'Text',
  'HbsAb': 'Text',
  'HBsAg': 'Text',
  'HBV': 'Text',
  'HCV': 'Text',
  'HDL-Cholesterol': 'mg/dL',
  'Hemoglobin (Hb)': 'g/dL',
  'Herpes Simplex I IgG (HSV)': 'Text',
  'Herpes Simplex I IgM (HSV)': 'Text',
  'Herpes Simplex II IgG (HSV)': 'Text',
  'Herpes Simplex II IgM (HSV)': 'Text',
  'HIV': 'Text',
  'HOMA-IR': '%',
  'INR': '%',
  'Insulin': 'U/ml',
  'Ionized Calcium': 'mg/dL',
  'Iron': 'µg/dL',
  'Lactate Dehydrogenase (LDH)': 'U/L',
  'LDL-Cholesterol': 'mg/dL',
  'LH': 'mIU/mL',
  'Lipase': 'U/L',
  'Lupus Anticoagulant': 'Sec',
  'Myoglobin': 'ug/mL',
  'OGTT': 'Rebort',
  'Para Thyroid Hormone (PTH)': 'pg/mL',
  'PCV': '%',
  'Phosphorus (P)': 'mg/dl',
  'Potassium ( K+ )': 'mmol/L',
  'Pregnancy (Serum)': 'Text',
  'proBNP': 'pg/mL',
  'Procalcitonin (PCT)': 'ng/mL',
  'Progesterone': 'ng/mL',
  'Prolactin': 'ng/mL',
  'PT': 'Sec',
  'Random Blood Sugar (RBS)': 'mg/dl',
  'RF latex': 'Text',
  'RF titer': 'IU/ml',
  'Rubella IgG': 'U/ml',
  'Rubella IgM': 'U/ml',
  'Seminal Fluid Analysis (SFA)': 'Rebort',
  'Sodium ( Na+ )': 'mmol/L',
  'Stool H.pylori (Ag)': 'Text',
  'Swab Culture': 'Rebort',
  'Syphilis': 'Text',
  'Testosterone': 'ng/ml',
  'Testosterone (Free)': 'pg/mL',
  'Thyroglobulin (TG)': 'ng/mL',
  'Thyroxine Test (T4)': 'µg/dL',
  'Tissue transglutaminase (Anti-tTG IgA)': 'U/mL',
  'Tissue transglutaminase (Anti-tTG IgG)': 'U/mL',
  'Total IgE': 'IU/ml',
  'Total iron binding capacity (TIBC)': 'µg/dL',
  'Total Protein': 'g/dL',
  'Total PSA': 'ng/mL',
  'TOXO IgG': 'Col',
  'TOXO IgM': 'Col',
  'Transferrin': 'g/L',
  'Triglycerides': 'mg / dl',
  'Triiodothyronine (T3)': 'ng/mL',
  'TSH': 'µIU/mL',
  'Typhoid IgG': 'Text',
  'Typhoid IgM': 'Text',
  'Urea': 'mg/dl',
  'Urea Breath Test (UBT)': 'DPM',
  'Uric Acid': 'mg/dl',
  'Urine Culture': 'Rebort',
  'VBG': 'Rebort',
  'Vitamin D': 'ng/ml',
  'Vitamin-B12': 'pg/ml',
  'VLDL-Cholesterol': 'mg/dL',
  'Zinc': 'µg/dL',
};
const lines = data.split(/\r?\n/);
let changed = 0;
let missing = [];
const regex = /^\s*\['المختبر',\s*'[^']+',\s*'([^']+)',\s*'[^']+',\s*'[^']+'\],\s*$/;
for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  const m = line.match(regex);
  if (m) {
    const name = m[1];
    const unit = mapping[name];
    if (unit !== undefined) {
      lines[i] = line.replace(/\],\s*$/, `, '${unit}'],`);
      changed++;
    } else {
      missing.push(name);
    }
  }
}
if (missing.length) {
  console.log('MISSING', missing.length, 'names:');
  console.log(missing.join('\n'));
}
console.log('CHANGED', changed);
fs.writeFileSync(path, lines.join('\n'), 'utf8');
