<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $updates = [
            1 => ['cat' => 'Hormone', 'price' => 8000],
            2 => ['cat' => 'Biochemistry', 'price' => 8000],
            3 => ['cat' => 'Biochemistry', 'price' => 20000],
            4 => ['cat' => 'Hematology', 'price' => 8000],
            5 => ['cat' => 'Hormone', 'price' => 8500],
            6 => ['cat' => 'Biochemistry', 'price' => 4000],
            7 => ['cat' => 'Biochemistry', 'price' => 4500],
            8 => ['cat' => 'Biochemistry', 'price' => 4000],
            10 => ['cat' => 'Biochemistry', 'price' => 4500],
            11 => ['cat' => 'Immunity', 'price' => 10000],
            12 => ['cat' => 'Immunity', 'price' => 10000],
            14 => ['cat' => 'Immunity', 'price' => 7000],
            15 => ['cat' => 'Immunity', 'price' => 7000],
            16 => ['cat' => 'Immunity', 'price' => 7000],
            17 => ['cat' => 'Immunity', 'price' => 7000],
            18 => ['cat' => 'Immunity', 'price' => 18000],
            19 => ['cat' => 'Hormone', 'price' => 24000],
            20 => ['cat' => 'Hormone', 'price' => 12000],
            21 => ['cat' => 'Hormone', 'price' => 12000],
            22 => ['cat' => 'Serology', 'price' => 4500],
            23 => ['cat' => 'Biochemistry', 'price' => 4000],
            24 => ['cat' => 'Hormone', 'price' => 8000],
            25 => ['cat' => 'Biochemistry', 'price' => 4000],
            27 => ['cat' => 'Biochemistry', 'price' => 4000],
            28 => ['cat' => 'Hematology', 'price' => 4000],
            29 => ['cat' => 'Microbiology', 'price' => 20000],
            30 => ['cat' => 'Hematology', 'price' => 4500],
            34 => ['cat' => 'Serology', 'price' => 4500],
            35 => ['cat' => 'Immunity', 'price' => 16000],
            36 => ['cat' => 'Immunity', 'price' => 16000],
            37 => ['cat' => 'Immunity', 'price' => 16000],
            38 => ['cat' => 'Hormone', 'price' => 20000],
            39 => ['cat' => 'Biochemistry', 'price' => 4500],
            40 => ['cat' => 'Immunity', 'price' => 17000],
            41 => ['cat' => 'Hormone', 'price' => 20000],
            43 => ['cat' => 'Hematology', 'price' => 8500],
            44 => ['cat' => 'Hematology', 'price' => 8500],
            45 => ['cat' => 'Immunity', 'price' => 16000],
            47 => ['cat' => 'Biochemistry', 'price' => 13000],
            48 => ['cat' => 'Biochemistry', 'price' => 4000],
            49 => ['cat' => 'Hormone', 'price' => 7000],
            50 => ['cat' => 'Infectious disease', 'price' => 8500],
            51 => ['cat' => 'Infectious disease', 'price' => 8500],
            52 => ['cat' => 'Immunity', 'price' => 10000],
            53 => ['cat' => 'Immunity', 'price' => 10000],
            54 => ['cat' => 'Biochemistry', 'price' => 12000],
            55 => ['cat' => 'Hormone', 'price' => 8500],
            57 => ['cat' => 'Hormone', 'price' => 20000],
            58 => ['cat' => 'Serology', 'price' => 4500],
            59 => ['cat' => 'Biochemistry', 'price' => 8500],
            60 => ['cat' => 'Biochemistry', 'price' => 4000],
            61 => ['cat' => 'Serology', 'price' => 4500],
            62 => ['cat' => 'Hormone', 'price' => 16000],
            63 => ['cat' => 'Hormone', 'price' => 20000],
            64 => ['cat' => 'Hematology', 'price' => 4500],
            65 => ['cat' => 'Hormone', 'price' => 8000],
            66 => ['cat' => 'Biochemistry', 'price' => 4000],
            67 => ['cat' => 'Hormone', 'price' => 8500],
            68 => ['cat' => 'Microbiology', 'price' => 4500],
            69 => ['cat' => 'Immunity', 'price' => 20000],
            70 => ['cat' => 'Hormone', 'price' => 8000],
            71 => ['cat' => 'Hormone', 'price' => 8000],
            72 => ['cat' => 'Microbiology', 'price' => 4500],
            73 => ['cat' => 'Microbiology', 'price' => 4000],
            74 => ['cat' => 'Biochemistry', 'price' => 4000],
            75 => ['cat' => 'Serology', 'price' => 4500],
            76 => ['cat' => 'Serology', 'price' => 4500],
            77 => ['cat' => 'Biochemistry', 'price' => 9500],
            78 => ['cat' => 'Infectious disease', 'price' => 8000],
            79 => ['cat' => 'Infectious disease', 'price' => 8000],
            80 => ['cat' => 'Infectious disease', 'price' => 11000],
            81 => ['cat' => 'Infectious disease', 'price' => 6000],
            82 => ['cat' => 'Infectious disease', 'price' => 8500],
            83 => ['cat' => 'Infectious disease', 'price' => 6000],
            84 => ['cat' => 'Biochemistry', 'price' => 4000],
            86 => ['cat' => 'Infectious disease', 'price' => 8500],
            87 => ['cat' => 'Infectious disease', 'price' => 8500],
            88 => ['cat' => 'Infectious disease', 'price' => 8500],
            89 => ['cat' => 'Infectious disease', 'price' => 8500],
            90 => ['cat' => 'Infectious disease', 'price' => 6000],
            91 => ['cat' => 'Hormone', 'price' => 20000],
            92 => ['cat' => 'Hematology', 'price' => 8000],
            93 => ['cat' => 'Hormone', 'price' => 16000],
            95 => ['cat' => 'Biochemistry', 'price' => 4500],
            96 => ['cat' => 'Biochemistry', 'price' => 4500],
            97 => ['cat' => 'Biochemistry', 'price' => 4000],
            98 => ['cat' => 'Hormone', 'price' => 8000],
            99 => ['cat' => 'Biochemistry', 'price' => 4500],
            100 => ['cat' => 'Hematology', 'price' => 30000],
            101 => ['cat' => 'Hormone', 'price' => 16000],
            102 => ['cat' => 'Hormone', 'price' => 10000],
            103 => ['cat' => 'Hormone', 'price' => 20000],
            105 => ['cat' => 'Biochemistry', 'price' => 4500],
            106 => ['cat' => 'Biochemistry', 'price' => 4500],
            107 => ['cat' => 'Serology', 'price' => 4000],
            109 => ['cat' => 'Immunity', 'price' => 21000],
            110 => ['cat' => 'Hormone', 'price' => 8000],
            111 => ['cat' => 'Hormone', 'price' => 8000],
            112 => ['cat' => 'Hematology', 'price' => 8000],
            113 => ['cat' => 'Biochemistry', 'price' => 4000],
            114 => ['cat' => 'Serology', 'price' => 4500],
            115 => ['cat' => 'Serology', 'price' => 4500],
            116 => ['cat' => 'Infectious disease', 'price' => 8500],
            117 => ['cat' => 'Infectious disease', 'price' => 8500],
            118 => ['cat' => 'Microbiology', 'price' => 8000],
            119 => ['cat' => 'Biochemistry', 'price' => 16000],
            120 => ['cat' => 'Serology', 'price' => 4500],
            121 => ['cat' => 'Microbiology', 'price' => 13000],
            122 => ['cat' => 'Serology', 'price' => 6000],
            123 => ['cat' => 'Hormone', 'price' => 8000],
            124 => ['cat' => 'Hormone', 'price' => 10000],
            125 => ['cat' => 'Hormone', 'price' => 12000],
            126 => ['cat' => 'Hormone', 'price' => 8000],
            127 => ['cat' => 'Immunity', 'price' => 7000],
            128 => ['cat' => 'Immunity', 'price' => 7000],
            129 => ['cat' => 'Immunity', 'price' => 15000],
            130 => ['cat' => 'Biochemistry', 'price' => 4500],
            131 => ['cat' => 'Biochemistry', 'price' => 4000],
            132 => ['cat' => 'Immunity', 'price' => 8500],
            133 => ['cat' => 'Infectious disease', 'price' => 8500],
            134 => ['cat' => 'Infectious disease', 'price' => 8500],
            135 => ['cat' => 'Immunity', 'price' => 20000],
            136 => ['cat' => 'Biochemistry', 'price' => 4000],
            137 => ['cat' => 'Hormone', 'price' => 8000],
            138 => ['cat' => 'Hormone', 'price' => 8000],
            139 => ['cat' => 'Serology', 'price' => 8000],
            140 => ['cat' => 'Serology', 'price' => 8000],
            141 => ['cat' => 'Biochemistry', 'price' => 4000],
            143 => ['cat' => 'Biochemistry', 'price' => 4000],
            144 => ['cat' => 'Microbiology', 'price' => 13000],
            146 => ['cat' => 'Hormone', 'price' => 12000],
            147 => ['cat' => 'Hormone', 'price' => 12000],
            149 => ['cat' => 'Biochemistry', 'price' => 12000],
            152 => ['cat' => 'Microbiology', 'price' => 8000],
        ];

        foreach ($updates as $id => $data) {
            DB::table('lab_tests')->where('id', $id)->update([
                'subcategory' => $data['cat'],
                'hi_price' => $data['price'],
                'is_hi_active' => true,
                'updated_at' => now(),
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
