<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MedicalDevice extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'type',
        'supplier',
        'price',
        'usage_price',
        'status',
        'serial_number',
        'last_maintenance_at',
        'purchase_date',
        'location_id'
    ];

    protected $casts = [
        'price' => 'decimal:2',
        'usage_price' => 'decimal:2',
        'last_maintenance_at' => 'date',
        'purchase_date' => 'date',
    ];

    /**
     * Get the location associated with the medical device.
     */
    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    /**
     * Get the surgeries associated with the medical device.
     */
    public function surgeries()
    {
        return $this->belongsToMany(Surgery::class, 'surgery_medical_device')
                    ->withPivot('assigned_by', 'price')
                    ->withTimestamps();
    }

    /**
     * Calculate total revenue generated by this device from all surgeries.
     */
    public function getTotalRevenueAttribute()
    {
        return (float) $this->surgeries()->sum('surgery_medical_device.price');
    }

    /**
     * Calculate cost recovery percentage.
     */
    public function getRecoveryPercentageAttribute()
    {
        if ($this->price <= 0) {
            return 0;
        }
        return min(100, round(($this->total_revenue / $this->price) * 100, 1));
    }
}
